name: Build and Publish to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          server-id: artifactory

      - name: Publish to Artifactory
        run: |
          export ARTIFACTORY_URL="https://your-artifactory-instance.com/artifactory"
          export ARTIFACTORY_REPO_KEY="your-repository"

          jfrog rt u "target/*.jar" "${ARTIFACTORY_REPO_KEY}/latest/" \
            --url=${ARTIFACTORY_URL} \
            --build-name=${{ github.repository }} \
            --build-number=${{ github.run_number }} \
            --flat=true
