name: Build and Publish to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        env:
          JFROG_CLI_LOG_LEVEL: INFO
          JFROG_CLI_OFFER_CONFIG: false
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Set Artifactory Config
        run: |
          jf c add artifactory \
          --interactive=false \
          --url=${{ secrets.ARTIFACTORY_URL }} \
          --user=${{ secrets.ARTIFACTORY_USER }} \
          --password=${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Set Maven Config
        run: |
          jf mvnc \
          --server-id-resolve=artifactory \
          --server-id-deploy=artifactory \

      - name: Build Maven Project
        run: |
          jf mvn clean install

      - name: Collect Build Info
        run: |
          jf rt u "target/*.jar" "${env.ARTIFACTORY_REPO_KEY}/latest/" \
            --url={{ secrets.ARTIFACTORY_URL }} \
            --build-name=${{ github.repository }} \
            --build-number=${{ github.run_number }} \
            --flat=true
