name: Build and Publish to Artifactory

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JFROG_CLI_LOG_LEVEL: INFO
          JFROG_CLI_OFFER_CONFIG: false
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.ARTIFACTORY_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Validate Artifactory Config
        run: |
          jf rt ping

      - name: Set Maven Config
        run: |
          jf mvnc \
          --repo-resolve-snapshots ${{ vars.ARTIFACTORY_SNAPSHOT_REPO }} \
          --repo-resolve-releases ${{ vars.ARTIFACTORY_RELEASES_REPO }} \
          --repo-deploy-snapshots ${{ vars.ARTIFACTORY_SNAPSHOT_REPO }} \
          --repo-deploy-releases ${{ vars.ARTIFACTORY_RELEASES_REPO }}

      - name: Build Maven Project
        run: |
          jf mvn clean install \
          --build-name=${{ github.repository }} \
          --build-number=${{ github.run_number }} \

      - name: Audit Dependencies
        run: |
          jf audit --mvn

      - name: Collect Build Environment Variables
        run: |
          jf rt bce ${{ github.repository }} ${{ github.run_number }}

      - name: Collect Git Information
        run: |
          jf rt bag ${{ github.repository }} ${{ github.run_number }}

      - name: Publish Build Info
        run: |
          jf rt bp ${{ github.repository }} ${{ github.run_number }}
