name: Promote and Create Release Candidate

on:
  push:
    tags:
      - '*-rc-[0-9]*' # Regex pattern to match tags suffixed with '-rc-' followed by a number

jobs:
  promote-and-create-release-candidate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v3
        with:
          version: latest
        env:
          JFROG_CLI_LOG_LEVEL: INFO
          JFROG_CLI_OFFER_CONFIG: false
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.ARTIFACTORY_USER }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}

      - name: Fetch Commit ID of Tagged Code
        id: tag_commit_id
        run: |
          echo "Commit ID: $(git rev-list -n 1 ${{ github.ref }})"

      - name: Print Tag Name
        run: |
          echo "Tag: ${{ github.ref }}"

      - name: Print Commit ID
        run: |
          echo "Commit ID: ${{ steps.tag_commit_id.outputs.tag_commit_id }}"

      - name: Promote Build to Release Candidate
        run: |
          jf rt bpr ${{ github.repository }} ${{ github.run_number }} ${{ vars.ARTIFACTORY_STAGE_REPO_KEY}} --status=staged --comment="Promoting build to release candidate"
